name: alpha

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

permissions: {}

jobs:
  build-image:
    name: Build image
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write
      id-token: write
    env:
      _USERNAME: fntyler
      _REPOSITORY_NAME: purple-workflow
    steps:
      - name: Check out repo
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.0.0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set metadata
        uses: docker/metadata-action@v5
        id: docker-meta
        with:
          images: ghcr.io/${{ env._USERNAME }}/${{ env._REPOSITORY_NAME }}
          tags: |
            type=ref,event=pr
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value={{branch}}-{{sha}},enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Build and Push container images
        uses: docker/build-push-action@v6.18.0
        id: build-and-push
        with:
          platforms: linux/amd64,linux/arm64
          file: docker/Dockerfile
          push: ${{ github.ref == 'refs/heads/main' }}
          outputs: type=oci,dest=purple-workflow-${{ github.sha }}.tar
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}

      - name: Debug
        env:
          GH_TOKEN: ${{ github.token }}
          DOCKER_METADATA_OUTPUT_JSON: ${{ steps.docker-meta.outputs.json }}
        run: |
          ls -la
          echo "github sha: ${{ github.sha }}"
          echo "github ref: ${{ github.ref }}"
          echo "github event: ${{ github.event.ref }}"
          echo "github event_name: ${{ github.event_name }}"
          echo "github event_path: ${{ github.event_path }}"

          echo "github job (job name): ${{ github.job }}"
          echo "github run id: ${{ github.run_id }}"

          job_id=$(gh api repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/jobs)
            #--jq '.jobs[] | select(.name == "${{ github.job }}") | .id')
            #--jq '.jobs[].id'
          echo "Github API job id: $job_id"

          echo "Docker metadata version: ${{ steps.docker-meta.outputs.version }}"
          echo "Docker metadata tags: ${{ steps.docker-meta.outputs.tags }}"
          echo "Docker metadata tag-names: ${{ steps.docker-meta.outputs.tag-names }}"
          echo "Docker metadata labels: ${{ steps.docker-meta.outputs.labels }}"
          echo "Docker metadata annotations: ${{ steps.docker-meta.outputs.annotations }}"
          echo "Docker metadata json: ${{ steps.docker-meta.outputs.json }}"

          echo "Docker metadata json parsed: ${{ fromJSON(steps.docker-meta.outputs.json).labels }}"
          echo "Docker metadata json parsed: ${{ fromJSON(steps.docker-meta.outputs.json).tag-names }}"

          echo "Docker imageid: ${{ steps.build-and-push.outputs.imageid }}"
          echo "Docker digest: ${{ steps.build-and-push.outputs.digest }}"
          echo "Docker metadata: ${{ steps.build-and-push.outputs.metadata }}" > docker.metadata.json

          echo "Docker metadata json env:"
          echo "$DOCKER_META_JSON" | jq '.'
          echo "$DOCKER_META_JSON" | jq -r '.tags[]'
          echo "$DOCKER_META_JSON" | jq -r '.labels | to_entries[] | "\(.key)=\(.value)"'


      - name: Upload tarball as artifact
        id: artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: purple-workflow-${{ github.sha }}.tar
          path: ./purple-workflow-${{ github.sha }}.tar
          if-no-files-found: warn
          retention-days: 7
          compression-level: 0

      - name: Upload tarball as artifact
        id: metadata-artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: docker.metadata.json
          path: ./docker.metadata.json
          if-no-files-found: warn
          retention-days: 7
          compression-level: 0

      - name: Sign and verify the images with GitHub OIDC Token
        if: github.ref == 'refs/heads/main'
        env:
          USERNAME: ${{ env._USERNAME }}
          REPOSITORY_NAME: ${{ env._REPOSITORY_NAME }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
          TAGS: ${{ steps.docker-meta.outputs.tags }}
          WORKFLOW_NAME: alpha.yml
          REF: ${{ github.ref }}
          COSIGN_REGISTRY: ghcr.io/${{ env._USERNAME }}/${{ env._REPOSITORY_NAME }}
        run: |
          images=""
          for tag in ${TAGS}; do
            images+="${tag}@${DIGEST} "
          done
          echo "Signing images: ${images}"
          cosign sign --yes ${images}
          echo "Verification starting..."
          cosign verify ${images} \
          --certificate-identity="https://github.com/${USERNAME}/${REPOSITORY_NAME}/.github/workflows/${WORKFLOW_NAME}@${REF}" \
          --certificate-oidc-issuer=https://token.actions.githubusercontent.com
          echo "Verification completed successfully"

